<?xml version="1.0"?>
<package format="3">
  <name>handeye_calibration_ros</name>
  <version>0.1.0</version>
  <description>The handeye_calibration_ros package</description>

  <maintainer email="agilex@todo.com">Your Name</maintainer>
  <license>Apache-2.0</license>  

  <!-- Dependencies -->
  <!-- <exec_depend>urdf</exec_depend> -->
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>aruco_ros</exec_depend>
  <exec_depend>piper</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
